name: kykms
services:
  kykms-mysql-comm:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
    restart: always
    container_name: kykms-mysql-comm
    image: sgccr.ccs.tencentyun.com/china/kykms:mysql
    volumes:
      - ./docker/mysql/conf/mysqld.cnf:/etc/mysql/conf.d/source/mysqld.cnf
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
    ports:
      - 3306:3306
    networks:
      kykms_network:

  kykms-redis-comm:
    image: sgccr.ccs.tencentyun.com/china/kykms:redis
    ports:
      - 6379:6379
    restart: always
    container_name: kykms-redis-comm
    volumes:
      - ./docker/redis/conf:/etc/redis
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    networks:
      kykms_network:

  kykms-ES-comm:
    image: sgccr.ccs.tencentyun.com/china/kykms:es
    restart: always
    container_name: kykms-ES-comm
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1G -Xmx2G"
      - TZ=Asia/Shanghai
    networks:
      kykms_network:

  kykms-comm:
    image: sgccr.ccs.tencentyun.com/china/kykms:api
    container_name: kykms-comm
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    depends_on:
      - kykms-mysql-comm
      - kykms-redis-comm
      - kykms-ES-comm
    ports:
      - "8080:8080"
    networks:
      kykms_network:
    restart: always
    command: java -jar ./app.jar ./catalina.out 2>&1 &

  kykms-nginx-comm:
    image: sgccr.ccs.tencentyun.com/china/kykms:web
    depends_on:
      - kykms-comm
    container_name: kykms-nginx-comm
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/log:/var/log/nginx
    networks:
      kykms_network:
    restart: always

networks:
  kykms_network:
    external: true
